<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);ToDoListApp.Tests\**</DefaultItemExcludes>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.7.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Resources\Images\app-logo.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
